import { type NextPage } from "next";
import Head from "next/head";
import { useUser } from "@clerk/nextjs";
import { Fragment } from "react";

const PostDetail: NextPage = () => {
  const { isLoaded: userLoaded } = useUser();

  if (!userLoaded) return <div />;

  return (
    <Fragment>
      <Head>
        <title>SocialStack 🥶</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          Post View
        </div>
      </main>
    </Fragment>
  );
};

export default PostDetail;
